---
# Tasks for installing and configuring Docker
- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: true
    state: present
  become: yes

- name: Add Docker GPG key
  command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  become: yes

- name: Add permissions to Docker GPG key
  command: chmod a+r /etc/apt/keyrings/docker.asc
  become: yes

- name: Add Docker repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename | lower }} stable"
    state: present
  become: yes

- name: Install docker engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
    state: present
  become: yes

- name: Create Docker daemon configuration directory
  file:
    path: /etc/docker
    state: directory
  become: yes

- name: Configure Docker daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  become: yes
  notify: "Restart docker service"

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: yes
  become: yes
