---
# Tasks for installing and configuring Sanoid for ZFS
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: apt

- name: Set install_sanoid variable
  set_fact:
    # This does not work
    # ansible_facts.packages[ 'sanoid' ].length == 0 or
    install_sanoid: >-
      {{
        ansible_facts.packages[ 'sanoid' ] is not defined or
        ansible_facts.packages[ 'sanoid' ][ 0 ].version != sanoid_version
      }}

- name: Download Sanoid
  get_url:
    url: "https://github.com/{{ sanoid_github_repo }}/releases/download/v{{ sanoid_version }}/sanoid_{{ sanoid_version }}_all.deb"
    dest: "/tmp/sanoid_{{ sanoid_version }}_all.deb"
  when: install_sanoid

- name: Install Sanoid
  apt:
    deb: "/tmp/sanoid_{{ sanoid_version }}_all.deb"
  when: install_sanoid
  become: yes

- name: Remove Sanoid debian package file
  file:
    path: "/tmp/sanoid_{{ sanoid_version }}_all.deb"
    state: absent
  when: install_sanoid

- name: Configure Sanoid
  template:
    src: sanoid.conf.j2
    dest: /etc/sanoid/sanoid.conf
  become: yes
  notify: "Start sanoid.timer service"
