---
# Tasks for installing and configuring ZFS for Docker
- name: Install ZFS utilities
  apt:
    name: zfsutils-linux
    state: present
  when: use_zfs_storage_driver or use_zfs_volume_plugin
  become: yes

- name: Create Docker storage driver ZFS dataset
  community.general.zfs:
    name: "{{ docker_zfs_pool_name }}/{{ docker_storage_driver_zfs_dataset_name }}"
    state: present
    extra_zfs_properties:
      mountpoint: "none"
  when: use_zfs_storage_driver
  become: yes

- name: Create Docker volume plugin ZFS dataset
  community.general.zfs:
    name: "{{ docker_zfs_pool_name }}/{{ docker_volume_plugin_zfs_dataset_name }}"
    state: present
    extra_zfs_properties:
      mountpoint: "/{{ docker_zfs_pool_name }}/{{ docker_volume_plugin_zfs_dataset_name }}"
  when: use_zfs_volume_plugin
  become: yes

- name: Download Docker ZFS plugin binary
  get_url:
    url: "https://github.com/{{ docker_zfs_plugin_github_repo }}/releases/download/{{ docker_zfs_plugin_version }}/docker-zfs-plugin"
    dest: /usr/local/bin/docker-zfs-plugin
    mode: '0755'
  when: use_zfs_volume_plugin
  become: yes

- name: Configure Docker ZFS plugin service
  template:
    src: docker-zfs-plugin.service.j2
    dest: /etc/systemd/system/docker-zfs-plugin.service
  when: use_zfs_volume_plugin
  become: yes
  notify: "Restart docker-zfs-plugin service"
