---
# Tasks for installing and configuring ZFS for Docker
- name: Install ZFS utilities
  apt:
    name: zfsutils-linux
    state: present
  when: use_zfs_storage_driver or use_zfs_volume_plugin
  become: yes

- name: Configure ZFS storage driver
  community.general.zfs:
    name: "{{ docker_zfs_pool_name }}/{{ docker_storage_driver_zfs_dataset_name }}"
    state: present
  when: use_zfs_storage_driver
  become: yes

- name: Configure ZFS volume plugin
  community.general.zfs:
    name: "{{ docker_zfs_pool_name }}/{{ docker_volume_plugin_zfs_dataset_name }}"
    state: present
  when: use_zfs_volume_plugin
  become: yes

- name: Download Docker ZFS plugin binary
  get_url:
    url: "https://github.com/{{ docker_zfs_plugin_github_repo }}/releases/download/{{ docker_zfs_plugin_version }}/docker-zfs-plugin"
    dest: /usr/local/bin/docker-zfs-plugin
    mode: '0755'
  when: use_zfs_volume_plugin
  become: yes

- name: Copy Docker ZFS plugin service file
  copy:
    src: docker-zfs-plugin.service
    dest: /etc/systemd/system/docker-zfs-plugin.service
  when: use_zfs_volume_plugin

- name: Start and enable Docker ZFS plugin service
  systemd:
    daemon_reload: yes
    name: docker-zfs-plugin
    enabled: yes
    state: started
  when: use_zfs_volume_plugin
  notify: Reload systemd and start docker-zfs-plugin
